### ISSUE TITLE
垃圾邮件

### ISSUE THREAD

**Issue by QwertyJack** [CAPU-ENG/CAPU-SA#3]
自从交流赛结束至今，本服务器邮件系统收到了一定量的（几十封）垃圾邮件。请各位大大检查是否有必要封禁本邮件系统。
邮件目录：~/mbox

**Comment by huxuan** [comment]
我们没有用服务器的邮件系统吧？还是我记错了？

**Comment by QwertyJack** [comment]
必须有 
域名chexie.net 
服务器sendmail
